[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "echo PORT=$PORT && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
