"""add passengers table

Revision ID: 28fbe1a05283
Revises: 5ae2dcd72a6a
Create Date: 2026-04-25 08:29:50.269298

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '28fbe1a05283'
down_revision: str | None = '5ae2dcd72a6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('passport_given_name', sa.String(length=64), nullable=False),
    sa.Column('passport_family_name', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('nationality', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('passport_number_enc', sa.String(length=512), nullable=True),
    sa.Column('passport_expiry_enc', sa.String(length=512), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers')
    # ### end Alembic commands ###
