"""add notify_email to price_alerts

Revision ID: a710e8f5cced
Revises: 28fbe1a05283
Create Date: 2026-04-25 08:51:14.643599

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a710e8f5cced'
down_revision: str | None = '28fbe1a05283'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_alerts', sa.Column('notify_email', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_alerts', 'notify_email')
    # ### end Alembic commands ###
